spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///goods?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true